pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - check-success=Evaluate flake.nix
      - check-success=package kexec-installer-nixos-2211 [x86_64-linux]
      - check-success=package kexec-installer-nixos-unstable [x86_64-linux]
      - check-success=package netboot-nixos-unstable [x86_64-linux]
      - check-success=check kexec-installer-unstable [x86_64-linux]
      - check-success=package netboot-nixos-2211 [x86_64-linux]
      - author=nix-eval-jobs-bot
    actions:
      merge:
        method: merge
      delete_head_branch: {}
